update:スピーカーブロックの音階定義を追加
SchooMyDevelopment/SchooMyUtilities pull request #9
Opened 2023-04-27 12:12 UTC by takumaushiroji-schoomy

## 関連Issue

close [スピーカーブロックの音階定義をSchooMyUtilitiesに移行する](https://github.com/SchooMyDevelopment/schoomy_block/issues/92)

## 目的 (Why)

- スピーカーブロックの音階定義が長いので、ライブラリに移行するため

## 内容 (What)

- 音階定義をSchooMyUtilitiesに移行した

## 影響範囲（Where）

- スピーカーブロック

## 動作確認 (How)

- ローカル環境

## Refs (レビューにあたって参考にすべき情報）(Optional)

- Schoomy_blockにも修正を加えています。

2023-05-10 12:10 UTC, naokiito-schoomy requested changes
スピーカーブロックの動作は問題ありませんでした。
1点だけ音階追加の対応をよろしくお願いします。

2023-05-10 12:10 UTC, naokiito-schoomy commented on SchooMyUtilities.h
> +      static const int F_BS4 = 1047;
音階を上に1オクターブ（C5～F_BS5）追加をお願いします。
付随してスピーカーブロックの修正（+2オクターブ）も必要になるので、合わせて対応をお願いします。

2023-05-17 11:06 UTC, takumaushiroji-schoomy commented on SchooMyUtilities.h
> +      static const int F_BS4 = 1047;
音階を追加しました。

2023-05-22 13:52 UTC, naokiito-schoomy approved these changes
指摘内容の修正を確認しました。

2023-05-23 00:32 UTC, ryoimayoshi-schoomy approved these changes
LGTM!

2023-05-23 00:33 UTC, merged